/**
 * gen_seal_vectors.cpp — emit cross-language test vectors for the sealed
 * envelope's symmetric half.
 *
 * WHY THIS TOOL EXISTS
 *
 * The C++ server and the JS browser client independently implement the same
 * derivation. If they disagree by one byte — a different HKDF salt convention,
 * a label with a stray space, a counter block treated as 64-bit instead of
 * 128-bit, UTF-8 versus UTF-16 when turning a label into bytes — the failure is
 * silent and looks exactly like a wrong password. It would be debugged as an
 * auth bug for a long time before anyone suspected the KDF.
 *
 * So the two sides are pinned to fixed byte strings, not to each other.
 *
 * The vectors deliberately cover only the SYMMETRIC layer — HKDF, AES-256-CTR,
 * HMAC-SHA-384 — starting from an already-agreed 64-byte master secret. That is
 * the part both sides implement independently, and it is the part a browser can
 * reproduce with WebCrypto alone. ML-KEM and X25519 produce the master and are
 * library calls on both sides, already covered by test_pqc.
 *
 * Inputs are generated from a counter rather than randomly: a vector file that
 * changes on every run cannot be committed, and one that cannot be committed
 * cannot detect a regression.
 *
 * Usage:  ./gen_seal_vectors > tests/seal_vectors.json
 */

#include "crypto/aead.h"
#include "crypto/base64.h"
#include "crypto/hkdf.h"
#include "crypto/secure_buffer.h"

#include <cstdint>
#include <iostream>
#include <string>
#include <vector>

using namespace chess::crypto;

namespace {

constexpr const char* CONTEXT = "CHESS-SEAL-1";

std::string to_hex(const uint8_t* d, size_t n) {
    static const char* HEX = "0123456789abcdef";
    std::string s;
    s.reserve(n * 2);
    for (size_t i = 0; i < n; ++i) {
        s.push_back(HEX[d[i] >> 4]);
        s.push_back(HEX[d[i] & 0x0F]);
    }
    return s;
}

std::string to_hex(const std::vector<uint8_t>& v) { return to_hex(v.data(), v.size()); }
std::string to_hex(const SecureBuffer& v)         { return to_hex(v.data(), v.size()); }

/// Deterministic filler so the file is byte-stable across runs and machines.
std::vector<uint8_t> filler(size_t n, uint8_t seed) {
    std::vector<uint8_t> v(n);
    for (size_t i = 0; i < n; ++i) {
        v[i] = static_cast<uint8_t>((i * 37 + seed * 101 + 17) & 0xFF);
    }
    return v;
}

} // namespace

int main() {
    // Payload lengths chosen around the AES block boundary, where a partial
    // final block is handled: 0, under, exactly, just over, and multi-block.
    const size_t lengths[] = {0, 1, 15, 16, 17, 31, 32, 33, 64, 100};

    std::cout << "{\n";
    std::cout << "  \"note\": \"Cross-language vectors for the sealed envelope's "
                 "symmetric layer. Generated by tools/gen_seal_vectors.cpp; "
                 "verified by tests/seal_vectors.mjs. Do not edit by hand.\",\n";
    std::cout << "  \"context\": \"" << CONTEXT << "\",\n";
    std::cout << "  \"kdf\": \"HKDF-SHA-384, empty salt\",\n";
    std::cout << "  \"enc_label\": \"" << CONTEXT << " enc\",\n";
    std::cout << "  \"mac_label\": \"" << CONTEXT << " mac\",\n";
    std::cout << "  \"aad\": \"CHESS-SEAL-1 || key_id\",\n";
    std::cout << "  \"mac_input\": \"be64(len(aad)) || aad || iv || ct\",\n";
    std::cout << "  \"vectors\": [\n";

    bool first = true;
    for (size_t idx = 0; idx < sizeof(lengths) / sizeof(lengths[0]); ++idx) {
        const uint8_t seed = static_cast<uint8_t>(idx + 1);

        // master = ss_mlkem || ss_x25519, 32 + 32 bytes
        const std::vector<uint8_t> master  = filler(64, seed);
        const std::vector<uint8_t> key_id  = filler(16, static_cast<uint8_t>(seed + 40));
        const std::vector<uint8_t> iv      = filler(16, static_cast<uint8_t>(seed + 80));
        const std::vector<uint8_t> payload = filler(lengths[idx],
                                                    static_cast<uint8_t>(seed + 120));

        SecureBuffer prk = HkdfSha384::extract(nullptr, 0, master.data(), master.size());
        AeadKeys keys = Aead::derive_keys(master.data(), master.size(), CONTEXT);

        std::vector<uint8_t> aad;
        aad.insert(aad.end(), CONTEXT, CONTEXT + std::string(CONTEXT).size());
        aad.insert(aad.end(), key_id.begin(), key_id.end());

        const std::vector<uint8_t> sealed =
            Aead::seal(keys, iv.data(), aad.data(), aad.size(),
                       payload.data(), payload.size());
        const size_t ct_len = payload.size();

        if (!first) std::cout << ",\n";
        first = false;

        std::cout << "    {\n"
                  << "      \"master\": \""  << to_hex(master)  << "\",\n"
                  << "      \"key_id\": \""  << to_hex(key_id)  << "\",\n"
                  << "      \"iv\": \""      << to_hex(iv)      << "\",\n"
                  << "      \"payload\": \"" << to_hex(payload) << "\",\n"
                  << "      \"prk\": \""     << to_hex(prk)     << "\",\n"
                  << "      \"k_enc\": \""   << to_hex(keys.enc)<< "\",\n"
                  << "      \"k_mac\": \""   << to_hex(keys.mac)<< "\",\n"
                  << "      \"ct\": \""      << to_hex(sealed.data(), ct_len) << "\",\n"
                  << "      \"tag\": \""     << to_hex(sealed.data() + ct_len,
                                                       sealed.size() - ct_len) << "\",\n"
                  << "      \"ct_b64\": \""  << encode_base64(sealed.data(), ct_len) << "\"\n"
                  << "    }";
    }

    std::cout << "\n  ]\n}\n";
    return 0;
}
